# Generated by Django 4.0.2 on 2022-02-23 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_question_question_detail_exam_is_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_in_exam', to='exam.question'),
        ),
    ]
