# Generated by Django 4.0.2 on 2022-03-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenexam',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
