# Generated by Django 4.0.2 on 2022-03-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_takenexam_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='autograde_output',
            field=models.TextField(default=''),
        ),
    ]
