# Generated by Django 4.0.2 on 2022-03-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_answer_autograde_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='autograded_points',
            new_name='name_autograde_points',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='points',
            new_name='name_points',
        ),
        migrations.AddField(
            model_name='answer',
            name='name_correct',
            field=models.BooleanField(default=False),
        ),
    ]
