# Generated by Django 4.0.2 on 2022-03-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_answertestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='name_max_points',
            field=models.FloatField(default=0),
        ),
    ]
